name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        mongodb-version: ['4.2', '4.4', '5.0']

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      env:
        ATLAS_USERNAME: ${{ secrets.CI_SECRETS.ATLAS_USERNAME }}
        ATLAS_PASSWORD: ${{ secrets.CI_SECRETS.ATLAS_PASSWORD }}
        ATLAS_TEST_USERNAME: ${{ secrets.CI_SECRETS.ATLAS_TEST_USERNAME }}
        ATLAS_TEST_PASSWORD: ${{ secrets.CI_SECRETS.ATLAS_PASSWORD }}
      run: npm test
